version: '3'

services:
  kvideo-lite:
    container_name: kvideo-lite
    image: vespeng/kvideo-lite:latest
    restart: always
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
